name: dress_pet
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  auto_size_text: ^3.0.0
  hugeicons: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/interface/
    - assets/img/wall/
    - assets/img/clothe/
    - assets/img/clothe/top/
    - assets/img/clothe/bottom/
    - assets/img/clothe/accessories/
    - assets/img/clothe/toys/
    - assets/img/menu/
    - assets/img/menu/top/
    - assets/img/menu/bottom/
    - assets/img/menu/accessories/
    - assets/img/menu/toys/
    - assets/img/menu/wall/

  fonts:
    - family: Figtree
      fonts:
        - asset: assets/font/Figtree-Regular.ttf
          weight: 400
        - asset: assets/font/Figtree-Bold.ttf
          weight: 700
        - asset: assets/font/Figtree-ExtraBold.ttf
          weight: 800

